/* AUTO-GENERATED by sim/run_all.py - do not edit by hand.
 * Tuned hybrid-FxLMS parameters (see sim/results/summary.md). */
#ifndef ANC_TUNING_H
#define ANC_TUNING_H

#define ANC_FS_HZ          32000u
#define ANC_L_FF           128u   /* feedforward taps */
#define ANC_L_FB           64u   /* adaptive feedback (IMC) taps */
#define ANC_L_S            64u   /* secondary-path model taps */
#define ANC_L_F            128u   /* speaker->ref-mic leakage model taps */
#define ANC_MU_FF          0.001f
#define ANC_MU_FB          0.0005f
#define ANC_LEAK           1e-05f
#define ANC_EPS            1e-06f
#define ANC_Y_MAX_PA       10.0f   /* output clamp, Pa at the ear */
#define ANC_WD_RATIO       3.98107171f
#define ANC_WD_HOLD        6400u
#define ANC_CLIP_TRIP      0.05f

/* error/filtered-reference weighting: 1st-order low-shelf 300 Hz, -20 dB floor */
#define ANC_W_B0           0.974243943f
#define ANC_W_B1           -0.968520374f
#define ANC_W_A1           -0.942764317f

/* 2nd-order Butterworth high-pass 30 Hz on x_c and d_hat */
#define ANC_HP_B0          0.99584346f
#define ANC_HP_B1          -1.99168692f
#define ANC_HP_B2          0.99584346f
#define ANC_HP_A1          -1.99166964f
#define ANC_HP_A2          0.991704196f

/* boot-time path identification */
#define ANC_ID_PROBE_PA    0.3f        /* ~83 dB SPL at the ear */
#define ANC_ID_SECONDS     3u
#define ANC_ID_MU_FACTORY  0.01f       /* quiet-room factory calibration */
#define ANC_ID_MU_REFINE   0.0005f     /* in-field refinement from the stored model */

#endif
