/* AUTO-GENERATED by sim/run_all.py - biquads as {b0, b1, b2, a1, a2} (a0 = 1). */
#ifndef DSP_COEFFS_H
#define DSP_COEFFS_H

/* IEC 61672 A-weighting at 32 kHz (dosimeter) */
#define SOS_AWEIGHT_N 3u
static const float SOS_AWEIGHT[3][5] = {
    {0.343458339f, 0.686916677f, 0.343458339f, 0.179471731f, 0.0080525256f},
    {1.0f, -2.0f, 1.0f, -1.84399066f, 0.846816324f},
    {1.0f, -2.0f, 1.0f, -1.99192712f, 0.991943411f}
};

/* hear-through speech band 300 Hz - 4 kHz */
#define SOS_HEARTHRU_N 2u
static const float SOS_HEARTHRU[2][5] = {
    {0.95920315f, -1.9184063f, 0.95920315f, -1.91674122f, 0.920071375f},
    {0.0976310729f, 0.195262146f, 0.0976310729f, -0.942809042f, 0.333333333f}
};

#endif
