/* AUTO-GENERATED by hardware/gen/pinmap.py - the schematic uses the same table. */
#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#define PIN_REF_L_PORT  GPIOA   /* PA6 (LQFP100 #30) ADC12_INP3 - left outside (reference) mic */
#define PIN_REF_L_PIN   6u
#define PIN_ERR_L_PORT  GPIOC   /* PC4 (LQFP100 #32) ADC12_INP4 - left inside (error) mic */
#define PIN_ERR_L_PIN   4u
#define PIN_REF_R_PORT  GPIOB   /* PB0 (LQFP100 #34) ADC12_INP9 - right reference mic (via satellite board) */
#define PIN_REF_R_PIN   0u
#define PIN_ERR_R_PORT  GPIOC   /* PC5 (LQFP100 #33) ADC12_INP8 - right error mic (via satellite board) */
#define PIN_ERR_R_PIN   5u
#define PIN_DAC_L_PORT  GPIOA   /* PA4 (LQFP100 #28) DAC1_OUT1 - left anti-noise out -> recon filter -> amp */
#define PIN_DAC_L_PIN   4u
#define PIN_DAC_R_PORT  GPIOA   /* PA5 (LQFP100 #29) DAC1_OUT2 - right anti-noise out */
#define PIN_DAC_R_PIN   5u
#define PIN_VBAT_SNS_PORT  GPIOC   /* PC0 (LQFP100 #15) ADC3_INP10 - battery / 2 */
#define PIN_VBAT_SNS_PIN   0u
#define PIN_USB_DM_PORT  GPIOA   /* PA11 (LQFP100 #70) AF10 - USB2_OTG_FS DM */
#define PIN_USB_DM_PIN   11u
#define PIN_USB_DP_PORT  GPIOA   /* PA12 (LQFP100 #71) AF10 - USB2_OTG_FS DP */
#define PIN_USB_DP_PIN   12u
#define PIN_VBUS_SNS_PORT  GPIOA   /* PA9 (LQFP100 #68) GPIO_IN - VBUS * 0.5 (USB present) */
#define PIN_VBUS_SNS_PIN   9u
#define PIN_SWDIO_PORT  GPIOA   /* PA13 (LQFP100 #72) SWD */
#define PIN_SWDIO_PIN   13u
#define PIN_SWCLK_PORT  GPIOA   /* PA14 (LQFP100 #76) SWD */
#define PIN_SWCLK_PIN   14u
#define PIN_SWO_PORT  GPIOB   /* PB3 (LQFP100 #89) SWO */
#define PIN_SWO_PIN   3u
#define PIN_DBG_TP_PORT  GPIOC   /* PC8 (LQFP100 #65) GPIO_OUT - ISR timing test point */
#define PIN_DBG_TP_PIN   8u
#define PIN_HSE_IN_PORT  GPIOH   /* PH0 (LQFP100 #12) OSC_IN - 25 MHz crystal */
#define PIN_HSE_IN_PIN   0u
#define PIN_HSE_OUT_PORT  GPIOH   /* PH1 (LQFP100 #13) OSC_OUT */
#define PIN_HSE_OUT_PIN   1u
#define PIN_BTN_PORT  GPIOC   /* PC13 (LQFP100 #7) GPIO_IN_PU - power/mode button sense via NPN inverter, active low */
#define PIN_BTN_PIN   13u
#define PIN_LED_R_PORT  GPIOE   /* PE9 (LQFP100 #39) TIM1_CH1 - RGB LED, common anode, active low */
#define PIN_LED_R_PIN   9u
#define PIN_LED_G_PORT  GPIOE   /* PE11 (LQFP100 #41) TIM1_CH2 */
#define PIN_LED_G_PIN   11u
#define PIN_LED_B_PORT  GPIOE   /* PE13 (LQFP100 #43) TIM1_CH3 */
#define PIN_LED_B_PIN   13u
#define PIN_PWR_HOLD_PORT  GPIOD   /* PD4 (LQFP100 #85) GPIO_OUT - keeps the buck-boost enabled after the button is released */
#define PIN_PWR_HOLD_PIN   4u
#define PIN_CHG_STAT_PORT  GPIOD   /* PD2 (LQFP100 #83) GPIO_IN_PU - MCP73831 STAT: low = charging */
#define PIN_CHG_STAT_PIN   2u
#define PIN_AMP_EN_PORT  GPIOD   /* PD0 (LQFP100 #81) GPIO_OUT - amp enable (mute when low) */
#define PIN_AMP_EN_PIN   0u
#define PIN_AMP_G0_PORT  GPIOD   /* PD1 (LQFP100 #82) GPIO_OUT - amp gain select bit 0 */
#define PIN_AMP_G0_PIN   1u
#define PIN_AMP_G1_PORT  GPIOD   /* PD3 (LQFP100 #84) GPIO_OUT - amp gain select bit 1 */
#define PIN_AMP_G1_PIN   3u
#define PIN_BLE_TX_PORT  GPIOD   /* PD8 (LQFP100 #55) USART3_TX AF7 - MCU TX -> module RX */
#define PIN_BLE_TX_PIN   8u
#define PIN_BLE_RX_PORT  GPIOD   /* PD9 (LQFP100 #56) USART3_RX AF7 - module TX -> MCU RX */
#define PIN_BLE_RX_PIN   9u
#define PIN_BLE_EN_PORT  GPIOD   /* PD10 (LQFP100 #57) GPIO_OUT - module enable / reset (high = run) */
#define PIN_BLE_EN_PIN   10u
#define PIN_BLE_STATE_PORT  GPIOD   /* PD11 (LQFP100 #58) GPIO_IN - module 'connected' status */
#define PIN_BLE_STATE_PIN   11u
#define PIN_I2C1_SCL_PORT  GPIOB   /* PB6 (LQFP100 #92) AF4 - spare, test pad (fuel gauge option) */
#define PIN_I2C1_SCL_PIN   6u
#define PIN_I2C1_SDA_PORT  GPIOB   /* PB7 (LQFP100 #93) AF4 - spare, test pad */
#define PIN_I2C1_SDA_PIN   7u

#endif
