/* AUTO-GENERATED by sim/run_all.py - biquads as {b0, b1, b2, a1, a2} (a0 = 1). */
#ifndef DSP_COEFFS_H
#define DSP_COEFFS_H

/* IEC 61672 A-weighting at 32 kHz (dosimeter) */
#define SOS_AWEIGHT_N 3u
static const float SOS_AWEIGHT[3][5] = {
    {0.343458339f, 0.686916677f, 0.343458339f, 0.179471731f, 0.0080525256f},
    {1.0f, -2.0f, 1.0f, -1.84399066f, 0.846816324f},
    {1.0f, -2.0f, 1.0f, -1.99192712f, 0.991943411f}
};

/* hear-through speech band 300 Hz - 4 kHz */
#define SOS_HEARTHRU_N 2u
static const float SOS_HEARTHRU[2][5] = {
    {0.95920315f, -1.9184063f, 0.95920315f, -1.91674122f, 0.920071375f},
    {0.0976310729f, 0.195262146f, 0.0976310729f, -0.942809042f, 0.333333333f}
};

/* seal monitor (sim/seal_ref.py): band b uses sections 2b, 2b+1 */
#define SEAL_NB 4u          /* octave bands 250, 500, 1000, 2000 Hz, 2 biquads each */
#define SEAL_GATE_DB 15.0f
#define SEAL_MIN_BAND_DB 55.0f
#define SEAL_FLAG_DB 3.0f
#define SEAL_HYST_DB 1.0f
#define SEAL_AVG_S 4.0f
#define SEAL_HOLD_S 3u
#define SOS_SEALBAND_N 8u
static const float SOS_SEALBAND[8][5] = {
    {0.000293952943f, 0.000587905886f, 0.000293952943f, -1.96585152f, 0.969801708f},
    {1.0f, -2.0f, 1.0f, -1.98031106f, 0.98174495f},
    {0.00114799511f, 0.00229599022f, 0.00114799511f, -1.92498456f, 0.940538327f},
    {1.0f, -2.0f, 1.0f, -1.95811771f, 0.963799653f},
    {0.00438253315f, 0.00876506631f, 0.00438253315f, -1.82454988f, 0.884787187f},
    {1.0f, -2.0f, 1.0f, -1.90643232f, 0.928727807f},
    {0.0160432653f, 0.0320865306f, 0.0160432653f, -1.55893681f, 0.784143424f},
    {1.0f, -2.0f, 1.0f, -1.77550827f, 0.861158845f}
};

#endif
